"""
In-memory task store + CRUD routes.
In production, swap the dict for Redis or Postgres.
"""
from __future__ import annotations

import io
import zipfile
from typing import Optional

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from app.models.task import Task, TaskCreate

router = APIRouter(prefix="/tasks", tags=["tasks"])

_store: dict[str, Task] = {}


def get_store() -> dict[str, Task]:
    return _store


@router.get("/", response_model=list[Task])
async def list_tasks(limit: int = 20, offset: int = 0):
    tasks = sorted(_store.values(), key=lambda t: t.created_at, reverse=True)
    return tasks[offset : offset + limit]


@router.get("/{task_id}", response_model=Task)
async def get_task(task_id: str):
    t = _store.get(task_id)
    if not t:
        raise HTTPException(status_code=404, detail="Task not found")
    return t


@router.delete("/{task_id}", status_code=204)
async def delete_task(task_id: str):
    if task_id not in _store:
        raise HTTPException(status_code=404, detail="Task not found")
    del _store[task_id]


@router.get("/{task_id}/download")
async def download_task_files(task_id: str):
    """Download all generated files as a ZIP archive."""
    t = _store.get(task_id)
    if not t:
        raise HTTPException(status_code=404, detail="Task not found")
    if not t.result or not t.result.files:
        raise HTTPException(status_code=404, detail="No files generated for this task")

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for filename, content in t.result.files.items():
            zf.writestr(filename, content)
        # Add a README
        zf.writestr(
            "TASK.md",
            f"# Task\n{t.description}\n\n"
            f"Generated by Manus Autonomous AI Engineer\n"
            f"Score: {t.result.evaluation.get('score', '?')}/10\n"
            f"Tokens used: {t.total_tokens}\n",
        )
    buf.seek(0)

    safe_name = t.description[:30].replace(" ", "_").replace("/", "_")
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="manus_{safe_name}.zip"'},
    )
